### ISSUE TITLE
Convert-Map-Markers: POI-Marker's `anchor` property is not populated correctly

### ISSUE THREAD

**Issue by TBlueF** [girugamoz/girugamoz.github.io#1]
When converting Dynmap-Markers into BlueMap's POI-Markers, the `anchor` property isn't set for the new icon.
Which means that icons won't be centered properly.

Related issue: https://github.com/BlueMap-Minecraft/BlueMap/issues/334

The best results in general would probably be to set it to the center of the icons, which might be tricky to do since your converter doesn't know the image-sizes. Alternatively setting the anchor to x0 y0 would not fully solve the issue, but be better than not setting it at all ^^

**Comment by girugamoz** [comment]
Sorry, for the delay, I hadn't yet setup notifications correctly for this repository.

AFAIU there is no equivalent to `anchor` in DynMap, correct?
I have added a new configuration option _Icon anchor mapping_.

Let me know what you think.

**Comment by TBlueF** [comment]
Perfect 👍 <3

**Comment by girugamoz** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/207854/189875783-1b3bdf3d-565b-45ef-b02c-d8f234edcde3.png)
