### ISSUE TITLE
An option to disable pretty printing

### ISSUE THREAD

**Issue by MiraculixxT** [girugamoz/girugamoz.github.io#2]
**Is your feature request related to a problem? Please describe.**
Currently i try to add a command for my BlueMap Marker addon to migrate internal markers to modifiable markers. That works pretty well, but i thought about taking a step further and add an option to directly insert them by entering the json string in console. The only problem are the line breaks. A version without any line breaks would bypass this issue

**Describe the solution you'd like**
Remove all line breaks and tabs from the json output

**Comment by mostenried** [comment]
I added a config option _Pretty print output_ to the bottom of the page. 
Let me know if this works for you.

**Comment by girugamoz** [comment]
I added a config option _Pretty print output_ to the bottom of the page.
Let me know if this works for you.

**Comment by MiraculixxT** [comment]
That is perfect! Thank you, it hopefully help people to integrate their dynmap markers
